version: '2.1'

services:
    localstack:
        container_name: '${LOCALSTACK_DOCKER_NAME-localstack_main}'
        image: localstack/localstack:0.12.5
        ports:
            - '4566:4566'
            - '${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}'
        environment:
            - SERVICES=${SERVICES- }
            - DEBUG=${DEBUG- }
            - DATA_DIR=${DATA_DIR- }
            - PORT_WEB_UI=${PORT_WEB_UI- }
            - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
            - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
            - DOCKER_HOST=unix:///var/run/docker.sock
        volumes:
            - '${TMPDIR:-/tmp/localstack}:/tmp/localstack'
            - '/var/run/docker.sock:/var/run/docker.sock'
