name: Build
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: foo
      AWS_SECRET_ACCESS_KEY: bar
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: yarn
      - name: build
        run: yarn run build
      - name: run localstack
        run: docker-compose build
      - name: run localstack
        run: docker-compose up -d
      - name: wait for localstack
        run: ./scripts/wait-for-url.js http://localhost:4575 && sleep 5
      - name: test
        run: yarn test
